<template>
  <section class="page"><header class="page-heading"><div><p class="eyebrow">Access management</p><h1>Users & Roles</h1><p class="subtitle">Manage system users, departments, and access levels.</p></div><button class="primary-button" type="button" @click="showForm = !showForm">{{ showForm ? 'Close Form' : 'Add User' }}</button></header><section v-if="showForm" class="panel user-form"><h2>Create user</h2><div class="form-grid"><label>Full Name<input v-model="form.name" placeholder="Full name" /></label><label>Email<input v-model="form.email" type="email" placeholder="name@tpa.go.tz" /></label><label>Role<select v-model="form.role"><option>Registrar</option><option>Administrator</option><option>Viewer</option></select></label><label>Department<input v-model="form.department" placeholder="Department" /></label></div><button class="primary-button" type="button" @click="addUser">Save User</button></section><section class="stats"><article><span>Total users</span><strong>{{ users.length }}</strong></article><article><span>Administrators</span><strong>{{ users.filter((user) => user.role === 'Administrator').length }}</strong></article><article><span>Active today</span><strong>8</strong></article></section><section class="panel table-panel"><div class="panel-heading"><h2>Registered users</h2><input v-model="search" placeholder="Search users" /></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Department</th><th>Last Login</th><th>Status</th></tr></thead><tbody><tr v-for="user in filteredUsers" :key="user.email"><td><strong>{{ user.name }}</strong></td><td>{{ user.email }}</td><td><span class="role">{{ user.role }}</span></td><td>{{ user.department }}</td><td>{{ user.lastLogin }}</td><td><span class="status active">Active</span></td></tr></tbody></table></div></section></section>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import { listUsers } from '@/services/api';
const search = ref(''); const showForm = ref(false); const form = reactive({ name: '', email: '', role: 'Registrar', department: '' });
const users = ref([]);
const filteredUsers = computed(() => users.value.filter((user) => Object.values(user).some((value) => String(value ?? '').toLowerCase().includes(search.value.toLowerCase()))));
onMounted(async () => { users.value = (await listUsers()).map((user) => ({ ...user, name: user.fullName || `${user.firstName || ''} ${user.lastName || ''}`.trim(), role: user.roles?.[0] || 'USER', department: '', lastLogin: 'Not available', status: user.enabled ? 'Active' : 'Inactive' })); });
function addUser() { if (!form.name || !form.email) return; users.value.unshift({ ...form, lastLogin: 'Never' }); Object.assign(form, { name: '', email: '', role: 'Registrar', department: '' }); showForm.value = false; }
</script>

<style scoped>
.page { max-width: 1100px; margin: 0 auto; }.page-heading,.panel-heading { align-items: center; display: flex; justify-content: space-between; gap: 16px; margin-bottom: 18px; }.eyebrow { color: #2E90C8; font-size: 11px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; }.page h1 { color: #1D2939; font-size: 24px; margin: 4px 0; }.subtitle { color: #7A8699; font-size: 13px; }.primary-button { background: #2E90C8; border: 0; border-radius: 5px; color: white; cursor: pointer; font-weight: 700; padding: 10px 14px; }.panel { background: white; border: 1px solid #DDE3EA; border-radius: 6px; padding: 18px; }.user-form { margin-bottom: 18px; }.panel h2 { color: #1D2939; font-size: 16px; margin: 0 0 16px; }.form-grid { display: grid; gap: 14px; grid-template-columns: repeat(4, 1fr); margin-bottom: 16px; }.form-grid label { color: #475467; display: grid; font-size: 12px; font-weight: 700; gap: 6px; }.form-grid input,.form-grid select,.panel-heading input { border: 1px solid #CDD5DF; border-radius: 5px; color: #344054; padding: 9px; }.stats { display: grid; gap: 14px; grid-template-columns: repeat(3, 1fr); margin-bottom: 18px; }.stats article { background: #F2F4F7; border-left: 3px solid #2E90C8; padding: 14px 16px; }.stats span { color: #667085; display: block; font-size: 12px; }.stats strong { color: #1D2939; display: block; font-size: 24px; margin-top: 5px; }.table-wrap { overflow-x: auto; }.table-panel table { border-collapse: collapse; min-width: 800px; width: 100%; }.table-panel th { background: #F2F4F7; color: #5D6C80; font-size: 12px; padding: 10px; text-align: left; }.table-panel td { border-bottom: 1px solid #E9EDF2; color: #3F4854; font-size: 13px; padding: 11px 10px; }.role { background: #E6F4FB; border-radius: 999px; color: #2674A8; font-size: 11px; font-weight: 700; padding: 4px 9px; }.status { border-radius: 999px; font-size: 11px; font-weight: 700; padding: 4px 10px; }.active { background: #D9F5E5; color: #16834D; }.panel-heading input { min-width: 220px; }
@media (max-width: 700px) { .page-heading,.panel-heading { align-items: flex-start; flex-direction: column; }.form-grid,.stats { grid-template-columns: 1fr; }.panel-heading input { min-width: 0; width: 100%; } }
</style>
