CREATE TABLE organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    code VARCHAR(255),
    description VARCHAR(255),
    parent_id BIGINT,
    CONSTRAINT fk_organizations_parent
        FOREIGN KEY (parent_id) REFERENCES organizations (id)
);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    account_non_expired BOOLEAN NOT NULL,
    account_non_locked BOOLEAN NOT NULL,
    credentials_non_expired BOOLEAN NOT NULL,
    organization_id BIGINT,
    CONSTRAINT fk_users_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role
        FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT fk_role_permissions_permission
        FOREIGN KEY (permission_id) REFERENCES permissions (id)
);

CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE station (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_type VARCHAR(255) NOT NULL,
    serial_number VARCHAR(255) NOT NULL UNIQUE,
    mac_address VARCHAR(255),
    brand VARCHAR(255),
    model VARCHAR(255),
    operating_system VARCHAR(255),
    warranty_start_date DATE,
    warranty_end_date DATE,
    status VARCHAR(255) NOT NULL,
    department_id BIGINT NOT NULL,
    station_id BIGINT NOT NULL,
    version BIGINT,
    CONSTRAINT fk_asset_department
        FOREIGN KEY (department_id) REFERENCES department (id),
    CONSTRAINT fk_asset_station
        FOREIGN KEY (station_id) REFERENCES station (id)
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id BIGINT,
    username VARCHAR(255),
    action VARCHAR(255) NOT NULL,
    resource_type VARCHAR(255),
    resource_id VARCHAR(255),
    http_method VARCHAR(255),
    endpoint VARCHAR(255),
    ip_address VARCHAR(255),
    user_agent VARCHAR(255),
    success BOOLEAN NOT NULL,
    previous_value TEXT,
    new_value TEXT,
    failure_reason VARCHAR(255),
    correlation_id VARCHAR(255),
    request_id VARCHAR(255)
);

CREATE TABLE assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    station_id BIGINT NOT NULL,
    assigned_date DATE NOT NULL,
    returned_date DATE,
    status VARCHAR(255) NOT NULL,
    CONSTRAINT fk_assignment_asset
        FOREIGN KEY (asset_id) REFERENCES asset (id),
    CONSTRAINT fk_assignment_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_assignment_station
        FOREIGN KEY (station_id) REFERENCES station (id),
    CONSTRAINT ck_assignment_status
        CHECK (status IN ('ACTIVE', 'RETURNED')),
    CONSTRAINT ck_assignment_dates
        CHECK (returned_date IS NULL OR returned_date >= assigned_date)
);

CREATE TABLE maintenance_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    service_date DATE NOT NULL,
    description VARCHAR(255) NOT NULL,
    logged_by BIGINT NOT NULL,
    CONSTRAINT fk_maintenance_record_asset
        FOREIGN KEY (asset_id) REFERENCES asset (id),
    CONSTRAINT fk_maintenance_record_user
        FOREIGN KEY (logged_by) REFERENCES users (id)
);

CREATE TABLE disposal_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    requested_by BIGINT NOT NULL,
    request_date DATE NOT NULL,
    status VARCHAR(255) NOT NULL,
    reason VARCHAR(255) NOT NULL,
    approved_by BIGINT,
    approval_date DATE,
    comments VARCHAR(255),
    CONSTRAINT fk_disposal_request_asset
        FOREIGN KEY (asset_id) REFERENCES asset (id),
    CONSTRAINT fk_disposal_request_requested_by
        FOREIGN KEY (requested_by) REFERENCES users (id),
    CONSTRAINT fk_disposal_request_approved_by
        FOREIGN KEY (approved_by) REFERENCES users (id),
    CONSTRAINT ck_disposal_request_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_disposal_request_dates
        CHECK (approval_date IS NULL OR approval_date >= request_date),
    CONSTRAINT ck_disposal_request_approval
        CHECK ((status = 'PENDING' AND approved_by IS NULL AND approval_date IS NULL)
            OR (status IN ('APPROVED', 'REJECTED') AND approved_by IS NOT NULL AND approval_date IS NOT NULL))
);