<template>
  <section class="page"><header class="page-heading"><div><p class="eyebrow">Asset lifecycle</p><h1>Maintenance</h1><p class="subtitle">Monitor repairs, service schedules, and assets currently out of service.</p></div><button class="primary-button" type="button" @click="showForm = !showForm">{{ showForm ? 'Close Form' : 'Log Maintenance' }}</button></header><section v-if="showForm" class="panel form-panel"><h2>Log maintenance activity</h2><div class="form-grid"><label>Asset<select v-model="form.asset"><option value="">Select asset</option><option v-for="asset in assets" :key="asset.id">{{ asset.serialNumber }}</option></select></label><label>Issue<input v-model="form.issue" placeholder="Describe the issue" /></label><label>Due Date<input v-model="form.dueDate" type="date" /></label><label>Technician<input v-model="form.technician" placeholder="Technician or vendor" /></label></div><button class="primary-button" type="button" @click="addRecord">Save Record</button></section><section class="stats"><article><span>Open work orders</span><strong>{{ records.filter((record) => record.status !== 'Completed').length }}</strong></article><article><span>Under maintenance</span><strong>{{ assets.filter((asset) => asset.status === 'Under Maintenance').length }}</strong></article><article><span>Completed this month</span><strong>12</strong></article></section><section class="panel table-panel"><div class="panel-heading"><h2>Maintenance work orders</h2><select v-model="filter"><option value="">All statuses</option><option>Scheduled</option><option>In Progress</option><option>Completed</option></select></div><div class="table-wrap"><table><thead><tr><th>Asset</th><th>Issue</th><th>Technician</th><th>Due Date</th><th>Status</th></tr></thead><tbody><tr v-for="record in filteredRecords" :key="record.asset"><td><strong>{{ record.asset }}</strong></td><td>{{ record.issue }}</td><td>{{ record.technician }}</td><td>{{ record.dueDate }}</td><td><span class="status" :class="record.status.toLowerCase().replace(' ', '-')">{{ record.status }}</span></td></tr></tbody></table></div></section></section>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import { createMaintenanceRecord, listAssets, listMaintenanceRecords } from '@/services/api';
const showForm = ref(false); const filter = ref(''); const form = reactive({ asset: '', issue: '', dueDate: '', technician: '' });
const assets = ref([]); const records = ref([]);
const filteredRecords = computed(() => records.value.filter((record) => !filter.value || record.status === filter.value));
onMounted(async () => {
  const [assetPage, recordPage] = await Promise.all([listAssets(), listMaintenanceRecords()]);
  assets.value = assetPage.data;
  records.value = recordPage.data.map((record) => ({ ...record, asset: `Asset ${record.assetId}`, issue: record.description, technician: `User ${record.loggedBy}`, dueDate: record.serviceDate, status: record.status || 'Completed' }));
});
async function addRecord() { const asset = assets.value.find((item) => item.serialNumber === form.asset); if (!asset || !form.issue) return; await createMaintenanceRecord({ assetId: asset.id, serviceDate: form.dueDate || new Date().toISOString().slice(0, 10), description: form.issue }); const response = await listMaintenanceRecords(); records.value = response.data.map((record) => ({ ...record, asset: `Asset ${record.assetId}`, issue: record.description, technician: `User ${record.loggedBy}`, dueDate: record.serviceDate, status: record.status || 'Completed' })); Object.assign(form, { asset: '', issue: '', dueDate: '', technician: '' }); showForm.value = false; }
</script>

<style scoped>
.page { max-width: 1100px; margin: 0 auto; }.page-heading,.panel-heading { align-items: center; display: flex; justify-content: space-between; gap: 16px; margin-bottom: 18px; }.eyebrow { color: #2E90C8; font-size: 11px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; }.page h1 { color: #1D2939; font-size: 24px; margin: 4px 0; }.subtitle { color: #7A8699; font-size: 13px; }.primary-button { background: #2E90C8; border: 0; border-radius: 5px; color: white; cursor: pointer; font-weight: 700; padding: 10px 14px; }.panel { background: white; border: 1px solid #DDE3EA; border-radius: 6px; padding: 18px; }.form-panel { margin-bottom: 18px; }.panel h2 { color: #1D2939; font-size: 16px; margin: 0 0 16px; }.form-grid { display: grid; gap: 14px; grid-template-columns: repeat(4, 1fr); margin-bottom: 16px; }.form-grid label { color: #475467; display: grid; font-size: 12px; font-weight: 700; gap: 6px; }.form-grid input,.form-grid select,.panel-heading select { border: 1px solid #CDD5DF; border-radius: 5px; color: #344054; padding: 9px; }.stats { display: grid; gap: 14px; grid-template-columns: repeat(3, 1fr); margin-bottom: 18px; }.stats article { background: #F2F4F7; border-left: 3px solid #2E90C8; padding: 14px 16px; }.stats span { color: #667085; display: block; font-size: 12px; }.stats strong { color: #1D2939; display: block; font-size: 24px; margin-top: 5px; }.table-wrap { overflow-x: auto; }.table-panel table { border-collapse: collapse; min-width: 700px; width: 100%; }.table-panel th { background: #F2F4F7; color: #5D6C80; font-size: 12px; padding: 10px; text-align: left; }.table-panel td { border-bottom: 1px solid #E9EDF2; color: #3F4854; font-size: 13px; padding: 11px 10px; }.status { border-radius: 999px; font-size: 11px; font-weight: 700; padding: 4px 10px; }.scheduled { background: #FFF0C7; color: #B66A00; }.in-progress { background: #DCEEFE; color: #2674A8; }.completed { background: #D9F5E5; color: #16834D; }
@media (max-width: 700px) { .page-heading,.panel-heading { align-items: flex-start; flex-direction: column; }.form-grid,.stats { grid-template-columns: 1fr; } }
</style>